language: node_js

node_js:
  - stable
  - 6
  - 5
  - 0.12
  - 0.10
  
install:
  - npm install

script: if [[ `node -v` == v0.10* ]]; then npm test; else npm run build && npm run cover; fi
  
after_script: 'npm run cover:report:coveralls'
