language: node_js
dist: trusty
sudo: false
cache: yarn

addons:
  apt:
    packages:
      - yarn

node_js:
  - stable
  - 6
  - 5
  - 0.12
  - 0.10

install: if [[ `node -v` == v0.1* ]]; then npm install; else yarn install; fi

script: if [[ `node -v` == v0.1* ]]; then npm test; else npm run build && npm run cover; fi

after_script: 'npm run cover:report:coveralls'
